# Generated by Django 4.0.1 on 2022-01-29 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_category_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
    ]
