 # Generated by Django 4.0.1 on 2022-01-31 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_category_id_alter_category_cat_id_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='income',
        ),
        migrations.AddField(
            model_name='transaction',
            name='amount',
            field=models.IntegerField(default=0, max_length=10),
        ),
    ]
